In [17]:
import torch
import os

In [2]:
x = torch.arange(12, dtype=torch.float32)

In [4]:
print(f"x: {x}\nX-type {type(x)}")

x: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
X-type <class 'torch.Tensor'>


In [5]:
x.shape

torch.Size([12])

In [8]:
X=x.reshape(-1,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
X.shape

torch.Size([3, 4])

In [10]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [11]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
X[1,2]=17

In [13]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
Z = torch.randn(4)
Z

tensor([ 1.1033,  0.7132,  0.8951, -0.0537])

In [21]:
import os
import csv
print(os.getcwd())

path = f"{os.getcwd()}/data"
data_file = os.path.join(path, 'house_tiny.csv')

header = ['NumRooms', 'RoofType', 'Price']
rows = [
    ['NA', 'NA', 127500],
    ['2', 'NA', 106000],
    ['4', 'Slate', 178100],
    ['NA', 'NA', 140000]
]

with open(data_file, 'w') as f:
  writer = csv.writer(f)
  writer.writerow(header)  # Write the header
  writer.writerows(rows)   # Write the data rows
        
print(f"CSV file created at {data_file}")

/Users/jojo/Downloads/Developer/MNIST
CSV file created at /Users/jojo/Downloads/Developer/MNIST/data/house_tiny.csv


In [22]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [23]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
print(targets)
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [24]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [25]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In this section we will be using Implementing linear regression using pytorch

In [26]:
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn

In [33]:
x= torch.tensor(range(-5,5)).float()
x.shape

torch.Size([10])

In [30]:
w_gt = 3
b_gt = 4
y = w_gt*x + b_gt
y

tensor([-11.,  -8.,  -5.,  -2.,   1.,   4.,   7.,  10.,  13.,  16.])

In [27]:
class LinearRegression(torch.nn.Module):
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear = torch.nn.Linear(1, 1, bias=True)  # bias is default True

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [28]:
lin_reg_model = LinearRegression()

In [36]:
# The Squared Loss is also known as 
# Mean Squared Error Loss to calculate the difference between the actual and predicted values.
criterion = torch.nn.MSELoss()
# The Stochastic Gradient Descent (SGD) optimizer is used to minimize the loss function.
# Allows to find the values of the parameters (weights) for the model that minimize the loss function.
optimizer = torch.optim.SGD(lin_reg_model.parameters(), lr=0.01)

In [37]:
def trainBuildIn(model, x, y, iter):
  for i in range(iter):
    # Clear gradient buffers because we don't want any gradient from previous epoch to carry forward, dont want to cummulate gradients
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y_pred, y)
    print(loss)
    loss.backward()
    optimizer.step()
    
    print(f'Iteration: {i} - Loss: {loss.item()}')

    

In [38]:
# x_train = x[:, None]
# y_train = y[:, None]
x_train = x.reshape(-1,1)
y_train = y.reshape(-1,1)

print(x.shape, x_train.shape)
print(y.shape, y_train.shape)

torch.Size([10]) torch.Size([10, 1])
torch.Size([10]) torch.Size([10, 1])


In [39]:
trainBuildIn(lin_reg_model, x_train, y_train, 10)

tensor(91.0960, grad_fn=<MseLossBackward0>)
Iteration: 0 - Loss: 91.09602355957031
tensor(66.2775, grad_fn=<MseLossBackward0>)
Iteration: 1 - Loss: 66.2774887084961
tensor(49.0686, grad_fn=<MseLossBackward0>)
Iteration: 2 - Loss: 49.0686149597168
tensor(37.0990, grad_fn=<MseLossBackward0>)
Iteration: 3 - Loss: 37.09897994995117
tensor(28.7380, grad_fn=<MseLossBackward0>)
Iteration: 4 - Loss: 28.738000869750977
tensor(22.8640, grad_fn=<MseLossBackward0>)
Iteration: 5 - Loss: 22.86395263671875
tensor(18.7051, grad_fn=<MseLossBackward0>)
Iteration: 6 - Loss: 18.705142974853516
tensor(15.7306, grad_fn=<MseLossBackward0>)
Iteration: 7 - Loss: 15.730611801147461
tensor(13.5750, grad_fn=<MseLossBackward0>)
Iteration: 8 - Loss: 13.574999809265137
tensor(11.9868, grad_fn=<MseLossBackward0>)
Iteration: 9 - Loss: 11.986841201782227
